"""
Pydantic models for database documents and API DTOs.
Provides type safety and validation across the system.
"""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum


class MessageRole(str, Enum):
    """Message role enum."""
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


# ============================================================================
# Collection Models (Database Documents)
# ============================================================================

class MessageDocument(BaseModel):
    """
    Message document stored in 'messages' collection.
    
    Represents a single conversation turn.
    """
    sessionId: str = Field(..., description="Session identifier")
    userId: str = Field(..., description="User identifier")
    role: MessageRole = Field(..., description="Message role")
    content: str = Field(..., description="Message content")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    createdAt: str = Field(..., description="ISO 8601 timestamp")
    timestamp: float = Field(..., description="Unix timestamp")
    
    class Config:
        json_schema_extra = {
            "example": {
                "sessionId": "session_123",
                "userId": "user_abc",
                "role": "user",
                "content": "What is the weather today?",
                "metadata": {},
                "createdAt": "2025-11-12T10:00:00.000Z",
                "timestamp": 1699790400.0
            }
        }


class SessionDocument(BaseModel):
    """
    Session document stored in 'sessions' collection.
    
    Tracks session metadata and long-term summary.
    """
    sessionId: str = Field(..., description="Session identifier")
    userId: str = Field(..., description="User identifier")
    summary: Optional[str] = Field(None, description="Long-term conversation summary")
    createdAt: str = Field(..., description="ISO 8601 timestamp")
    updatedAt: str = Field(..., description="ISO 8601 timestamp")
    
    class Config:
        json_schema_extra = {
            "example": {
                "sessionId": "session_123",
                "userId": "user_abc",
                "summary": "User asked about weather and travel plans...",
                "createdAt": "2025-11-12T10:00:00.000Z",
                "updatedAt": "2025-11-12T11:30:00.000Z"
            }
        }


class ToolCallLog(BaseModel):
    """
    Tool call log document stored in 'tool_calls' collection.
    
    Tracks all DB tool invocations for observability.
    """
    sessionId: str = Field(..., description="Session identifier")
    userId: str = Field(..., description="User identifier")
    tool: str = Field(..., description="Tool name (e.g., 'db.find')")
    args: Dict[str, Any] = Field(..., description="Tool arguments")
    result: Dict[str, Any] = Field(..., description="Tool result")
    latency_ms: float = Field(..., description="Execution latency in milliseconds")
    timestamp: str = Field(..., description="ISO 8601 timestamp")
    
    class Config:
        json_schema_extra = {
            "example": {
                "sessionId": "session_123",
                "userId": "user_abc",
                "tool": "db.find",
                "args": {
                    "collection": "messages",
                    "filter": {"sessionId": "session_123"},
                    "limit": 50
                },
                "result": {
                    "status": "ok",
                    "count": 10
                },
                "latency_ms": 7.5,
                "timestamp": "2025-11-12T10:00:00.000Z"
            }
        }


class SuggestionDocument(BaseModel):
    """
    Suggestion document stored in 'suggestions' collection.
    
    Tracks follow-up suggestions generated by Synthesizer.
    """
    sessionId: str = Field(..., description="Session identifier")
    userId: str = Field(..., description="User identifier")
    messageId: str = Field(..., description="Associated assistant message ID")
    suggestions: List[str] = Field(..., description="List of 3 suggestions")
    createdAt: str = Field(..., description="ISO 8601 timestamp")
    
    class Config:
        json_schema_extra = {
            "example": {
                "sessionId": "session_123",
                "userId": "user_abc",
                "messageId": "msg_456",
                "suggestions": [
                    "Show me more details",
                    "What are the next steps?",
                    "Can you summarize?"
                ],
                "createdAt": "2025-11-12T10:00:00.000Z"
            }
        }


class MetricsDocument(BaseModel):
    """
    Metrics document stored in 'metrics' collection.
    
    Tracks performance metrics for each request.
    """
    sessionId: str = Field(..., description="Session identifier")
    userId: str = Field(..., description="User identifier")
    messageId: str = Field(..., description="Associated assistant message ID")
    ttft_ms: Optional[float] = Field(None, description="Time to first token (ms)")
    total_time_ms: Optional[float] = Field(None, description="Total request time (ms)")
    tool_call_count: int = Field(0, description="Number of tool calls")
    agent_timings: Dict[str, float] = Field(default_factory=dict, description="Per-agent timings")
    timestamp: str = Field(..., description="ISO 8601 timestamp")
    
    class Config:
        json_schema_extra = {
            "example": {
                "sessionId": "session_123",
                "userId": "user_abc",
                "messageId": "msg_456",
                "ttft_ms": 150.5,
                "total_time_ms": 2345.8,
                "tool_call_count": 2,
                "agent_timings": {
                    "planner": 120.3,
                    "worker": 500.2,
                    "critic": 80.1,
                    "synthesizer": 200.5
                },
                "timestamp": "2025-11-12T10:00:00.000Z"
            }
        }


# ============================================================================
# API Request/Response Models
# ============================================================================

class ChatRequest(BaseModel):
    """Request model for /v1/chat/stream endpoint."""
    sessionId: str = Field(..., description="Session identifier")
    userId: str = Field(..., description="User identifier")
    prompt: str = Field(..., min_length=1, description="User prompt")
    
    class Config:
        json_schema_extra = {
            "example": {
                "sessionId": "session_123",
                "userId": "user_abc",
                "prompt": "Summarize our last discussion and propose next steps."
            }
        }


class ChatResponse(BaseModel):
    """Response model for chat completion."""
    fullText: str = Field(..., description="Complete assistant response")
    suggestions: List[str] = Field(..., description="3 follow-up suggestions")
    timings: Dict[str, Any] = Field(..., description="Performance timings")
    
    class Config:
        json_schema_extra = {
            "example": {
                "fullText": "Based on our discussion...",
                "suggestions": [
                    "Show more details",
                    "Next steps?",
                    "Summarize key points"
                ],
                "timings": {
                    "requestStart": 1699790400.0,
                    "firstTokenAt": 1699790400.5,
                    "completedAt": 1699790402.5,
                    "ttft_ms": 500.0,
                    "total_ms": 2500.0
                }
            }
        }


class SessionResponse(BaseModel):
    """Response model for session retrieval."""
    sessionId: str
    userId: str
    summary: Optional[str]
    messageCount: int
    createdAt: str
    updatedAt: str
    
    class Config:
        json_schema_extra = {
            "example": {
                "sessionId": "session_123",
                "userId": "user_abc",
                "summary": "Discussion about AI and ML...",
                "messageCount": 24,
                "createdAt": "2025-11-12T10:00:00.000Z",
                "updatedAt": "2025-11-12T12:00:00.000Z"
            }
        }


class SuggestionResponse(BaseModel):
    """Response model for suggestions retrieval."""
    messageId: str
    suggestions: List[str]
    createdAt: str


class MetricsResponse(BaseModel):
    """Response model for metrics retrieval."""
    sessionId: str
    totalRequests: int
    avgTtftMs: Optional[float]
    avgTotalTimeMs: Optional[float]
    totalToolCalls: int
    
    class Config:
        json_schema_extra = {
            "example": {
                "sessionId": "session_123",
                "totalRequests": 15,
                "avgTtftMs": 180.5,
                "avgTotalTimeMs": 2100.3,
                "totalToolCalls": 45
            }
        }


class HealthResponse(BaseModel):
    """Response model for health check."""
    status: str = Field(..., description="Health status")
    database: str = Field(..., description="Database health")
    timestamp: str = Field(..., description="Check timestamp")
    
    class Config:
        json_schema_extra = {
            "example": {
                "status": "healthy",
                "database": "connected",
                "timestamp": "2025-11-12T10:00:00.000Z"
            }
        }


class VitalsResponse(BaseModel):
    """Response model for system vitals."""
    uptime_seconds: float
    total_sessions: int
    total_messages: int
    total_tool_calls: int
    avg_response_time_ms: Optional[float]
    
    class Config:
        json_schema_extra = {
            "example": {
                "uptime_seconds": 3600.5,
                "total_sessions": 42,
                "total_messages": 356,
                "total_tool_calls": 128,
                "avg_response_time_ms": 1850.3
            }
        }